[package]
name = "zhang-suen"
version = "0.1.0"
authors = ["WhizSid <whizsid@aol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"
imgthin = {path="../../" , features = ["improved_ysc_whh"] }
